=== Cause-effect principle

From Joshua's perspective, reasoning means understanding if one event (the solution of a problem) can be the final effect of a chain of occurrences of cause-effect relationships. To verify the existance of such type of chain, Joshue leverage on a predefined knowledge and a state.

A knowledge includes a set of events, and a set of cause-effect relationships.
A state is just a set of variables.

Even if Joshua is able to increase the knowledge deriving new cause-effect relationships, it needs a starting knowledge, since is not able to build one from scratch. Building a knowledge requires the ability to observe (by senses) and analyze (by reasoning) events, in order to produce new cause-effect relationships.

=== Events

An event is a phenomenon which can always happen or it can happen under certain circumstances. Technically, an event is defined by:

* a human readable description of the event itself
* an **optional** list of condition, where each condition is a mathematical equation
* an **optional** list of assignments, where each assigment change the value of a specific variable

=== Cause-effect relationships

A cause-effect relationship ties two events, defining that the happening of one event (cause) "may" trigger the happening of another one.

For Joshua there are two different type of relationships:

* **always true relationships** declares that the happening of event X **always** trigger the happening of event Y
* **possible relationship** declares that the happening of event X **may** trigger the happening of event Y

Thus every relationship has a weight, and the latter is a number into the interval [0,1] such that:

* 0 means that the event X **never** triggers the event Y
* 1 means that the event X **always** triggers the event Y
* any value in (0,1) means that the event X **may** trigger the event Y

=== State

The state is a set of variables, whose values can determine if an event can happen, as well as the values can be altered by the occurrence of events.

Managing a state is important to solve some type of problems, where the solution is determinated by reaching specific values of some variables.

=== Solving problems

When Joshua loads a knowledge file and transforms it into a directed, weighted graph, where events are the nodes and relationships are the arcs. 

[NOTE]
====
Givan a graph, solving a problems means asking the question: **is there a concatenation of cause-effect relationships that terminate into the desidered effect?**
====

When a problem is only related to "always true relationships", then finding out a solution means finding out a path between a cause and an effect into the knowledge's graph. In this case, we say that Joshua is operating like a "rules manager".

Differently, when the occurrence of events are bound to a specific state, then the reasoning is harder. Joshua treats the graph as a kind of state machine, the path from the source event to the desired effect can be really long, and the same cause-effect relationship may occur multiple times.

=== Be able to describe the problem

An effective description of the problem is everything (Joshua is not able to do that by itself).

Looking from Joshua's eyes, describing a problems involves an iterative process of four steps:

. Which event represents the problem's solution?
. Which others events are possible?
. Which cause-effect relationship has the problem's solution as effect?
. Which others relationships are possible?

If some events can occur only if a specific state is reached, then it is necessary to define the state too.

Next paragraph explain the process of describing a problem throughout an example.