== Joshua

**Joshua** is a software inspired by a book footnote:[Incoscienza Artificiale - Massimo Chiriatti - https://www.ibs.it/incoscienza-artificiale-come-fanno-macchine-libro-massimo-chiriatti/e/9788861056312?inventoryId=275963946] to solve a **problem** using a combination of **knowledge** and **state**.

The _knowledge_ consists of **events** and **relationships** between events.

An _event_ is _something_ that occurs under certain circumstances, for example the event "the farmer reaches the est bank of the river" can occur if the farmer is not on the est bank of the river.

A _relationship_ ties two events by means of **cause-effect** principe, thus the occurrence of an event may cause the occurrence of other events.

The _state_ includes the information which determine if an event may happen or not;  the occurrence of an event may change the current _state_.

How can Joshua solve a problem?::
A _problem_ is described as the combination of: 
. a _knowledge_
. an initial _state_
. the _final event_, that is the event you would like to make happen.

Finding a solution for a problem means checking if there is **at least one chain of events that eventually cause the final event**.