== Joshua

**Joshua** is a software inspired by a book footnote:[Incoscienza Artificiale - Massimo Chiriatti - https://www.ibs.it/incoscienza-artificiale-come-fanno-macchine-libro-massimo-chiriatti/e/9788861056312?inventoryId=275963946] to solve **problems** using a combination of **knowledge** and **state**.

The _knowledge_ consists of **events** and **relationships** between events.

An _event_ is _something_ that occurs under certain circumstances described by a _state_; for example the event "the farmer reaches the est bank of the river" can occur if the farmer is not on the est bank of the river.

The _state_ includes information which determine if events may happen or not,  as well as the occurrence of events may change the _state_.

Finally, the _relationships_ tie events by means of **cause-effect** principle, thus the occurrence of an event may cause the occurrence of other events.

How can Joshua solve a problem?::
A _problem_ is described as the combination of (i) the _knowledge_, (ii) an initial _state_ and (iii) a _final event_, the latter is the event you would check the occurrence.

In these terms, finding a solution for a problem means checking if there is **at least one chain of events that eventually cause the final event**.

Joshua can have different applications, and it can be view as a simple _rule engine_.